apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-flink-script
  labels:
    app: flink
data:
  bootstrap.sh: |
    #!/bin/bash
    set -ex
    set -o pipefail

    echo "启动用hadoop fs命令创建flink history的存储目录...."
    hadoop fs -mkdir -p /flink/completed-jobs
    echo "启动flink history ...."
    /opt/flink/bin/historyserver.sh start
    sleep 10
    tail -F /opt/flink/log/*.log
