apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-kyuubi
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Release.Name}}-kyuubi-cluster-role
  namespace: {{.Release.Namespace}}
rules:
  - apiGroups: [""]
    resources: ["pods","services"]
    verbs: ["get", "watch", "list", "create", "delete","patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Name}}-kyuubi-cluster-role-binding
  namespace: {{.Release.Namespace}}
subjects:
  - kind: ServiceAccount
    name: {{.Release.Name}}-kyuubi
    namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{.Release.Name}}-kyuubi-cluster-role
  apiGroup: rbac.authorization.k8s.io
