{
 "title": "Hive Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Hive Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "HIVE_HiveServer2_hs2_active_sessions_Value{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "HIVE_HiveServer2_hs2_open_sessions_Value{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Avg Active Session Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "HIVE_HiveServer2_hs2_avg_active_session_time_Value{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Avg Open Session Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "HIVE_HiveServer2_hs2_avg_open_session_time_Value{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open File Descriptor Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "HIVE_HiveServer2_OS_OpenFileDescriptorCount{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Max File Descriptor Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "HIVE_HiveServer2_OS_MaxFileDescriptorCount{pod=~\"demo-hive-server-(.*)\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Daemon Thread Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "HIVE_HiveServer2_Threading_DaemonThreadCount{pod=~\"demo-hive-server-(.*)\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "HIVE_HiveServer2_Threading_ThreadCount{pod=~\"demo-hive-server-(.*)\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{pod=~\"demo-hive-server2-(.*)\"}[5m])*100) by (pod)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"demo-hive-server2-(.*)\"}) by (pod)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(HIVE_HiveServer2_Memory_heap_used{}) by (pod)",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "sum(HIVE_HiveServer2_Memory_heap_committed{}) by (pod)",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "sum(HIVE_HiveServer2_Memory_heap_max{}) by (pod)",
     "legendFormat": "{{pod}}-max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(HIVE_HiveServer2_Memory_non_heap_used{}) by (pod)",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "sum(HIVE_HiveServer2_Memory_non_heap_committed{}) by (pod)",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "sum(HIVE_HiveServer2_Memory_non_heap_max{}) by (pod)",
     "legendFormat": "{{pod}}-max"
    }
   ]
  },
  {
   "title": "Hive Metastore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Created Connections",
   "type": "stat",
   "description": "Return total number of connections created in all partitions.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(HIVE_HiveMetaStore_BoneCP_TotalCreatedConnections{})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections Requested",
   "type": "stat",
   "description": "Returns the connectionsRequested field.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(HIVE_HiveMetaStore_BoneCP_ConnectionsRequested{})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Free Connections",
   "type": "stat",
   "description": "Return the number of free connections available to an application right away (excluding connections that can be created dynamically)",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(HIVE_HiveMetaStore_BoneCP_TotalFree{})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Calls API Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(HIVE_HiveMetaStore_active_calls_api{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Thread Runnable Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(HIVE_HiveMetaStore_Threads_runnable_count{})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(HIVE_HiveMetaStore_Threading_ThreadCount{})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Daemon Thread Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(HIVE_HiveMetaStore_Threading_DaemonThreadCount{})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{pod=~\"demo-hive-metastore-(\\\\d+)\"}[5m])*100) by (pod)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"demo-hive-metastore-(\\\\d+)\"}) by (pod)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(HIVE_HiveMetaStore_Memory_heap_used{}) by (pod)",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "sum(HIVE_HiveMetaStore_Memory_heap_committed{}) by (pod)",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "sum(HIVE_HiveMetaStore_Memory_heap_max{}) by (pod)",
     "legendFormat": "{{pod}}-max"
    }
   ]
  },
  {
   "title": "JVM NonHeap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(HIVE_HiveMetaStore_Memory_non_heap_used{}) by (pod)",
     "legendFormat": "{{pod}}-used"
    },
    {
     "expr": "sum(HIVE_HiveMetaStore_Memory_non_heap_committed{}) by (pod)",
     "legendFormat": "{{pod}}-committed"
    },
    {
     "expr": "sum(HIVE_HiveMetaStore_Memory_non_heap_max{}) by (pod)",
     "legendFormat": "{{pod}}-max"
    }
   ]
  },
  {
   "title": "Connection Wait Time Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "HIVE_HiveMetaStore_BoneCP_ConnectionWaitTimeAvg{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Calls API Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(HIVE_HiveMetaStore_calls_api{type=\"Count\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}