apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-hive-metastore-headless
  labels:
    app: hive-metastore
spec:
  ports:
    - port: 9083
      protocol: TCP
      name: hms
    - port: 8007
      protocol: TCP
      name: metrics
  selector:
    app: hive-metastore
  clusterIP: None
  publishNotReadyAddresses: true

