apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-hive-server2-svc
spec:
  ports:
    - port: 10000
      protocol: TCP
      name: hs2
    - port: 10002
      protocol: TCP
      name: ui
    - port: 8007
      protocol: TCP
      name: jmx
  selector:
    app: hive-server2
