apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}-hive-server2
  labels:
    app: hive-server2
spec:
  serviceName: {{.Release.Name}}-hive-server2-headless
  replicas: {{.Values.server2.replicas}}
  selector:
    matchLabels:
      app: hive-server2
  template:
    metadata:
      labels:
        app: hive-server2
    spec:
      nodeSelector:
      {{ toYaml .Values.server2.nodeSelector | indent 8 }}
      containers:
        {{ if .Values.metrics.jmx.enable}}
        - name: jmx-exporter
          env:
            - name: SERVICE_PORT
              value: "8007"
          image: {{.Values.metrics.jmx.image}}
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 8007
          volumeMounts:
            - name: jmx-config
              mountPath: /opt/jmx_exporter/config.yml
              subPath: hive-server-config.yml
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /metrics
              port: 8007
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 60
          readinessProbe:
            failureThreshold: 8
            httpGet:
              path: /metrics
              port: 8007
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 60
        {{end}}
        - name: hive-server2
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /
              port: server2-ui
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 60
          readinessProbe:
            failureThreshold: 8
            httpGet:
              path: /
              port: server2-ui
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 60
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: HADOOP_HOME
              value: "/usr/local/hadoop"
            - name: HIVE_CONF_DIR
              value: "/opt/hive/conf"
            - name: HADOOP_HEAPSIZE
              value: "1024"
          image: {{.Values.image}}
          command:  [ "/bin/bash", "-ce", "/opt/start-hiveserver2.sh" ]
          imagePullPolicy: Always
          ports:
            - name: server2-port
              containerPort: 10000
              protocol: TCP
            - name: server2-ui
              containerPort: 10002
              protocol: TCP
          volumeMounts:
            - name: hiveconf
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
            - name: hiveconf
              mountPath: /opt/hive/conf/hive-log4j2.properties
              subPath: hive-log4j2.properties
            - name: hadoop-fs-conf
              mountPath: /usr/local/hadoop/etc/hadoop/core-site.xml
              subPath: core-site.xml
            - name: hiveconf
              mountPath: /opt/hive/conf/hive-env.sh
              subPath: hive-env.sh
            - name: hadoop-fs-conf
              mountPath: /usr/local/hadoop/etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: hadoop-yarn-conf
              mountPath: /usr/local/hadoop/etc/hadoop/yarn-site.xml
              subPath: yarn-site.xml
            - name: hadoop-yarn-conf
              mountPath: /usr/local/hadoop/etc/hadoop/mapred-site.xml
              subPath: mapred-site.xml
            - name: hive-script
              mountPath: /opt/start-hiveserver2.sh
              subPath: start-hiveserver2.sh
          resources:
            requests:
              memory: "2G"
              cpu: "2"
      volumes:
        - name: jmx-config
          configMap:
            name: {{.Release.Name}}-hive-jmx-configmap
        - name: hive-script
          configMap:
            name: {{.Release.Name}}-hive-script
            defaultMode: 0744
        - name: hiveconf
          configMap:
            name: {{.Release.Name}}-hive-cfg
        - name: hadoop-fs-conf
          configMap:
            name: {{template "hadoop-fs-conf" .}}
        - name: hadoop-yarn-conf
          configMap:
            name: {{template "hadoop-yarn-conf" .}}
