apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-hive-server2-headless
  labels:
    app: hive-server2
spec:
  ports:
    - port: 10000
      protocol: TCP
      name: hs2
    - port: 10002
      protocol: TCP
      name: ui
    - port: 8007
      protocol: TCP
      name: metrics
  selector:
    app: hive-server2
  clusterIP: None

