apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-juicefs-script
  labels:
    app: juicefs
data:
  bootstrap.sh: |
                  #!/bin/bash
                  set -ex
                  set -o pipefail

                  echo "开始格式化 ...."
                  # format juicefs
                  juicefs format  --storage $STORAGE \
                  --bucket $BUCKET \
                  --access-key $ACCESS_KEY \
                  --secret-key $SECRET_KEY \
                  $META_URL \
                  myjfs

                  echo "开始挂载到本地盘 ....  "
                  juicefs mount $META_URL -d juicefs_mnt

                  echo "开始启动 juicefs  gateway...."
                  juicefs gateway $META_URL :9100

